USE PractiseManagementSystemProject_kta
GO
SET DATEFORMAT dmy; 

--Please note that all information inserted in this DB does not relate to any real person. 

--Insert Patient
INSERT INTO PATIENT (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship) VALUES ('Carlo', 'Farett', '20/06/1994 12:00:00 AM', 24, 'Male', '18 Elizabeth St', 'Sydney', '2036', '2060', 'Australia', 'MEDICARE-CF-001', CONVERT(datetime, '18/06/2018 2:15:29 AM', 103), CONVERT(datetime, '18/06/2018 2:15:29 AM', 103), 'Home', '0415662789', 'carloFarett@pms.com.au', 'Manarva Farett', '0427881897', 'Mother')
INSERT INTO PATIENT (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship) VALUES ('Samantha', 'Laczon', '15/03/1988 12:00:00 AM', 30, 'Female', '12 York St', 'Cammeray', 'NSW', '2061', 'Australia', 'MEDI-SL-002', CONVERT(datetime, '18/06/2018 2:20:29 AM', 103), CONVERT(datetime, '18/06/2018 2:20:29 AM', 103), 'Office', '0429876112', 'sLaczon@test.com', 'Ferdinand Laczon', '0425674456', 'Father')


--Insert Employee-Doctor
SET DATEFORMAT dmy; INSERT INTO EMPLOYEE (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship, companyName,companyAddress, position, jobTitle, employeeStatus, department, hireDate, employmentType, incomeType, incomeAmount, hoursWorked, startTime) VALUES ('Bea', 'Madrigal', '7/08/1979 12:00:00 AM', 39, 'Female', '10 Atchison St', 'St Leonards', 'NSW', '2065', 'Australia', 'DR-MEDI-BM-002', CONVERT(datetime, '18/06/2018 4:10:35 AM', 103), CONVERT(datetime, '18/06/2018 4:10:35 AM', 103), 'Office', '0417662543', 'bMadrigal@medcentre.com.au', 'Beverly', 'Madrigal', 'Sister', 'MedCentre Hospital', 'Hornsby', 'Executive', 'Doctor', 'Active', 'Psychologist Department', CONVERT(datetime, '8/11/2013 12:00:00 AM', 103), 'Full-Time', 'Annually', '200000', 5, CONVERT(TIME, '12:00 PM'))
INSERT INTO DOCTOR (employeeId, doctorLicenseNo, specialty, buildingLocation, roomNumber) VALUES ((SELECT IDENT_CURRENT('EMPLOYEE')),'LIC-BM8391Y', 'Clinical Psychiatrist', 'MedCentre Tower IV', '10F-1005')
SET DATEFORMAT dmy; INSERT INTO EMPLOYEE (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship, companyName,companyAddress, position, jobTitle, employeeStatus, department, hireDate, employmentType, incomeType, incomeAmount, hoursWorked, startTime) VALUES ('Harold', 'Gutchires', '28/06/1978 12:00:00 AM', 40, 'Decline to State', 'Macquarie St', 'Sydney', 'NSW', '2000', 'Australia', 'DR-MEDIHG1978-001', CONVERT(datetime, '18/06/2018 6:30:47 AM', 103), CONVERT(datetime, '18/06/2018 6:30:47 AM', 103), 'Home', '04132268821', 'HGutchi@hci.com.au', 'Andrew', 'Hamilton', 'Step-Brother', 'HealthCare Institute', 'Macquarie St', 'Executive', 'Doctor', 'Inactive', 'Basic Nursing Department', CONVERT(datetime, '12/01/2017 12:00:00 AM', 103), 'Part-Time', 'Hourly', '30', 5, CONVERT(TIME, '10:00 AM'))
INSERT INTO DOCTOR (employeeId, doctorLicenseNo, specialty, buildingLocation, roomNumber) VALUES ((SELECT IDENT_CURRENT('EMPLOYEE')),'LIC-HG1978H', 'Pediatric Endocrinology', 'HCI Building 2', '7F-7012')

--Insert Employee - Receptionist
SET DATEFORMAT dmy; INSERT INTO EMPLOYEE (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship, companyName,companyAddress, position, jobTitle, employeeStatus, department, hireDate, employmentType, incomeType, incomeAmount, hoursWorked, startTime) VALUES ('Margo', 'Santos', '11/10/1995 12:00:00 AM', 23, 'Female', '11 Rosamond St', 'Hornsby', 'NSW', '2077', 'Australia', 'R-MEDI-MS-001', CONVERT(datetime, '18/06/2018 4:17:08 AM', 103), CONVERT(datetime, '18/06/2018 4:17:08 AM', 103), 'Office', '826337892', 'mSantos@medcentre.com.au', 'Darlene Vanigen', '654267116', 'GrandMother', 'MedCentre Hospital', 'Hornsby', 'Staff', 'Receptionist', 'Active', 'General Department', CONVERT(datetime, '28/04/2016 12:00:00 AM', 103), 'Full-Time', 'Annually', '', 7, CONVERT(TIME, '7:00 AM'))

--Insert Employee - Admin
SET DATEFORMAT dmy; INSERT INTO EMPLOYEE (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship, companyName,companyAddress, position, jobTitle, employeeStatus, department, hireDate, employmentType, incomeType, incomeAmount, hoursWorked, startTime) VALUES ('Gabby', 'Thompson', '24/02/1969 12:00:00 AM', 49, 'Male', 'Park St', 'Bella Vista', 'NSW', '2033', 'Australia', 'ADMEDI-GT-001', CONVERT(datetime, '18/06/2018 4:34:08 AM', 103), CONVERT(datetime, '18/06/2018 4:34:08 AM', 103), 'Office', '2668730911', 'gab_thompson@gmail.com', 'Tera Thompson', '787721891', 'Wife', 'IT TechSoft Corp', 'Sydney', 'Admin', 'Admin', 'Active', 'General Department', CONVERT(datetime, '7/08/2014 12:00:00 AM', 103), 'Part-Time', 'Annually', '', 4, CONVERT(TIME, '1:00 PM'))

--Insert Employee - Nurse
SET DATEFORMAT dmy; INSERT INTO EMPLOYEE (firstName, lastName, dob, age, gender, address1, suburb, state, postcode, country, medicareNo, recordCreated, recordUpdated,contactType, contactNo, emailAddress, emergencyContactName, emergencyContactNo, relationship, companyName,companyAddress, position, jobTitle, employeeStatus, department, hireDate, employmentType, incomeType, incomeAmount, hoursWorked, startTime) VALUES ('Kriza', 'Ohm', '20/06/1992 12:00:00 AM', 26, 'Female', 'Kings St', 'Parramata', 'NSW', '2000', 'Australia', 'NS-MEDI-KO-002', CONVERT(datetime, '18/06/2018 4:38:41 AM', 103), CONVERT(datetime, '18/06/2018 4:38:41 AM', 103), 'Mobile', '0423118273', 'kOhm@medcentre.com.au', 'Lawrence Twain', '035266188', 'Husband', 'Medcentre Hospital', 'Hornsby', 'Staff', 'Nurse', 'Active', 'General Department', CONVERT(datetime, '5/12/2017 12:00:00 AM', 103), 'Full-Time', 'Annually', '80000', 10, CONVERT(TIME, '10:00 AM'))

--Add Appointment
--NOTE:  PLEASE CREATE A NEW APPOINTMENT IN THE FORM, THIS IS MORE EASIER

--Add Medical Records
--NOTE: PLEASE CREATE A NEW APPOINTMENT IN THE FORM, THIS IS MORE EASIER

